# Generated by Django 4.2.4 on 2023-08-24 15:17

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.blog.models.blog_directory_path),
        ),
    ]
